### ISSUE TITLE
根目录：文件夹路径的问题

### ISSUE THREAD

**Issue by BaronDuan** [bubbliiiing/deeplabv3-plus-pytorch#75]
一直报错：FileNotFoundError: [Errno 2] No such file or directory:，但是文件路径明明没有问题啊
<img width="788" alt="image" src="https://github.com/bubbliiiing/deeplabv3-plus-pytorch/assets/133481614/af92d241-8e8a-460d-902b-6b352e997ce4">
文件都摆放好了，train.txt也没问题，在ImageSet里的segmentation里面都生成好了，但还是一直报错

**Comment by bubbliiiing** [comment]
额，看看错误

**Comment by 1366332545** [comment]
raceback (most recent call last):
  File "c:\GitHub\deeplabv3-plus-pytorch\train.py", line 516, in <module>
    fit_one_epoch(model_train, model, loss_history, eval_callback, optimizer, epoch,
  File "c:\GitHub\deeplabv3-plus-pytorch\utils\utils_fit.py", line 24, in fit_one_epoch
    for iteration, batch in enumerate(gen):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 1359, in _process_data
    data.reraise()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\_utils.py", line 543, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "c:\GitHub\deeplabv3-plus-pytorch\utils\dataloader.py", line 32, in __getitem__
    jpg         = Image.open(os.path.join(os.path.join(self.dataset_path, "VOC2007/JPEGImages"), name + ".jpg"))
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\Image.py", line 3236, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'VOCdevkit\\VOC2007/JPEGImages\\01684-2665506724-Old.jpg'

**Comment by bubbliiiing** [comment]
VOCdevkit\VOC2007/JPEGImages\01684-2665506724-Old.jpg这个文件看看
