### ISSUE TITLE
文件路径问题，用下好的VOC文件夹就没问题，用自己做的数据集一训练就出现这个错误

### ISSUE THREAD

**Issue by 1366332545** [bubbliiiing/deeplabv3-plus-pytorch#84]

**Comment by 1366332545** [comment]
raceback (most recent call last):
  File "c:\GitHub\deeplabv3-plus-pytorch\train.py", line 516, in <module>
    fit_one_epoch(model_train, model, loss_history, eval_callback, optimizer, epoch,
  File "c:\GitHub\deeplabv3-plus-pytorch\utils\utils_fit.py", line 24, in fit_one_epoch
    for iteration, batch in enumerate(gen):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 1359, in _process_data
    data.reraise()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\_utils.py", line 543, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "c:\GitHub\deeplabv3-plus-pytorch\utils\dataloader.py", line 32, in __getitem__
    jpg         = Image.open(os.path.join(os.path.join(self.dataset_path, "VOC2007/JPEGImages"), name + ".jpg"))
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\Image.py", line 3236, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'VOCdevkit\\VOC2007/JPEGImages\\01684-2665506724-Old.jpg'

**Comment by bubbliiiing** [comment]
额，你的路径错了哦0 0

**Comment by 1366332545** [comment]
大佬，主要我是跟着视频一步一步做的，路径啥的都没改过，会不会跟我数据训练量太少有关，只有100多张。救救孩子吧

**Comment by bubbliiiing** [comment]
不是的……你是不是后缀不是jpg

**Comment by 1366332545** [comment]
博主，路径修改好了，模型也练好了，但是无法预测。
===>background: Iou-76.14; Recall (equal to the PA)-100.0; Precision-76.14
===>win:        Iou-0.0; Recall (equal to the PA)-0.0; Precision-0.0
===>door:       Iou-0.0; Recall (equal to the PA)-0.0; Precision-0.0
===> mIoU: 25.38; mPA: 33.33; Accuracy: 76.14
不知道是不是因为我标签.png图片是黑色背景，其他标注红、绿色标注，而不是像视频中白色底，黑色标注框的问题？

**Comment by bubbliiiing** [comment]
应该不是0 0，labelme出来本来就是这样。也需要应该看看数据0 0，但为什么background这种情况下不应该为1吗

**Comment by qiqi0911** [comment]
> 博主，路径修改好了，模型也练好了，但是无法预测。 ===>background: Iou-76.14; Recall (equal to the PA)-100.0; Precision-76.14 ===>win: Iou-0.0; Recall (equal to the PA)-0.0; Precision-0.0 ===>door: Iou-0.0; Recall (equal to the PA)-0.0; Precision-0.0 ===> mIoU: 25.38; mPA: 33.33; Accuracy: 76.14 不知道是不是因为我标签.png图片是黑色背景，其他标注红、绿色标注，而不是像视频中白色底，黑色标注框的问题？

你好，请问一下我也出现了路径错误问题，您是怎么解决的呀
