### ISSUE TITLE
损失函数路径问题

### ISSUE THREAD

**Issue by FCMzp05** [bubbliiiing/deeplabv3-plus-pytorch#94]
Traceback (most recent call last):
  File "c:\Users\pc\Desktop\语义分割\deeplabv3-plus-pytorch-main\train.py", line 322, in <module>
    loss_history    = LossHistory(log_dir, model, input_shape=input_shape)
  File "c:\Users\pc\Desktop\语义分割\deeplabv3-plus-pytorch-main\utils\callbacks.py", line 29, in __init__
    self.writer     = SummaryWriter(self.log_dir)
  File "C:\Users\pc\anaconda3\envs\sdsd_torch\lib\site-packages\torch\utils\tensorboard\writer.py", line 247, in __init__
    self._get_file_writer()
  File "C:\Users\pc\anaconda3\envs\sdsd_torch\lib\site-packages\torch\utils\tensorboard\writer.py", line 277, in _get_file_writer
    self.file_writer = FileWriter(
  File "C:\Users\pc\anaconda3\envs\sdsd_torch\lib\site-packages\torch\utils\tensorboard\writer.py", line 76, in __init__
    self.event_writer = EventFileWriter(
  File "C:\Users\pc\anaconda3\envs\sdsd_torch\lib\site-packages\tensorboard\summary\writer\event_file_writer.py", line 72, in __init__
    tf.io.gfile.makedirs(logdir)
  File "C:\Users\pc\anaconda3\envs\sdsd_torch\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 513, in recursive_create_dir_v2
    _pywrap_file_io.RecursivelyCreateDir(compat.path_to_bytes(path))
tensorflow.python.framework.errors_impl.FailedPreconditionError: C:/Users/pc/Desktop/语义分割/deeplabv3-plus-pytorch-main\loss_2023_11_12_13_36_21 is not a directory
请问这个是为什么？之前yolov5做目标检测也报了这样的错误，换成v7就可以了，现在做语义分割也这样报错

**Comment by FCMzp05** [comment]
已经解决了，路径不能有中文

**Comment by ylj183** [comment]
请问损失函数在哪个文件里面呀
